// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/payments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "List payments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Subscription ID filter",
                        "name": "subscription_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Provider filter",
                        "name": "provider",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Create a payment",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.CreatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentResponse"
                        }
                    }
                }
            }
        },
        "/payments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Get a payment by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Delete a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.MessageResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Update a payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdatePaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentResponse"
                        }
                    }
                }
            }
        },
        "/payments/{id}/status": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments-service"
                ],
                "summary": "Update payment status from a payment provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Payment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdatePaymentStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.MessageResponse"
                        }
                    }
                }
            }
        },
        "/plans": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "List plans",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Active filter",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Interval filter",
                        "name": "interval",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "Create a plan",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.CreatePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanResponse"
                        }
                    }
                }
            }
        },
        "/plans/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "Get a plan by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "Delete a plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.MessageResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plans"
                ],
                "summary": "Update a plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Plan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdatePlanRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness probe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/subscriptions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "List subscriptions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Owner ID filter",
                        "name": "owner_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Plan ID filter",
                        "name": "plan_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order",
                        "name": "sort_order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Create a subscription",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.CreateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Get a subscription by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Delete a subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.MessageResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions"
                ],
                "summary": "Update a subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdateSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionResponse"
                        }
                    }
                }
            }
        },
        "/subscriptions/{id}/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscriptions-service"
                ],
                "summary": "Get subscription status for service validation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.CreatePaymentRequest": {
            "type": "object",
            "required": [
                "amount_cents",
                "currency",
                "provider"
            ],
            "properties": {
                "amount_cents": {
                    "type": "integer",
                    "minimum": 0
                },
                "currency": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.JSONMap"
                },
                "provider": {
                    "type": "string",
                    "maxLength": 64
                },
                "provider_payment_id": {
                    "type": "string",
                    "maxLength": 255
                },
                "subscription_id": {
                    "type": "string"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.CreatePlanRequest": {
            "type": "object",
            "required": [
                "currency",
                "interval",
                "name"
            ],
            "properties": {
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 1024
                },
                "features": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.JSONMap"
                },
                "interval": {
                    "enum": [
                        "monthly",
                        "yearly",
                        "one_time"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanInterval"
                        }
                    ]
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 120,
                    "minLength": 2
                },
                "price_cents": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.CreateSubscriptionRequest": {
            "type": "object",
            "required": [
                "plan_id"
            ],
            "properties": {
                "plan_id": {
                    "type": "string"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.JSONMap": {
            "type": "object",
            "additionalProperties": {}
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentListResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentResponse": {
            "type": "object",
            "properties": {
                "amount_cents": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.JSONMap"
                },
                "owner_id": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "provider_payment_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentStatus"
                },
                "subscription_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentStatus": {
            "type": "string",
            "enum": [
                "pending",
                "completed",
                "failed",
                "refunded"
            ],
            "x-enum-varnames": [
                "PaymentPending",
                "PaymentCompleted",
                "PaymentFailed",
                "PaymentRefunded"
            ]
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanInterval": {
            "type": "string",
            "enum": [
                "monthly",
                "yearly",
                "one_time"
            ],
            "x-enum-varnames": [
                "PlanIntervalMonthly",
                "PlanIntervalYearly",
                "PlanIntervalOneTime"
            ]
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanListResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "plans": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "features": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.JSONMap"
                },
                "id": {
                    "type": "string"
                },
                "interval": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanInterval"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "price_cents": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionListResponse": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "subscriptions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionResponse"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "canceled_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "current_period_end": {
                    "type": "string"
                },
                "current_period_start": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionStatus"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionStatus": {
            "type": "string",
            "enum": [
                "active",
                "canceled",
                "expired",
                "past_due"
            ],
            "x-enum-varnames": [
                "SubscriptionActive",
                "SubscriptionCanceled",
                "SubscriptionExpired",
                "SubscriptionPastDue"
            ]
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdatePaymentRequest": {
            "type": "object",
            "properties": {
                "metadata": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.JSONMap"
                },
                "provider_payment_id": {
                    "type": "string",
                    "maxLength": 255
                },
                "status": {
                    "enum": [
                        "pending",
                        "completed",
                        "failed",
                        "refunded"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentStatus"
                        }
                    ]
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdatePaymentStatusRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "enum": [
                        "pending",
                        "completed",
                        "failed",
                        "refunded"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PaymentStatus"
                        }
                    ]
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdatePlanRequest": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "maxLength": 1024
                },
                "features": {
                    "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.JSONMap"
                },
                "interval": {
                    "enum": [
                        "monthly",
                        "yearly",
                        "one_time"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.PlanInterval"
                        }
                    ]
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 120,
                    "minLength": 2
                },
                "price_cents": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.UpdateSubscriptionRequest": {
            "type": "object",
            "properties": {
                "canceled_at": {
                    "type": "string"
                },
                "current_period_end": {
                    "type": "string"
                },
                "current_period_start": {
                    "type": "string"
                },
                "status": {
                    "enum": [
                        "active",
                        "canceled",
                        "expired",
                        "past_due"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_teaspeak-v2_wt-bot-ms-payments-v1_internal_models.SubscriptionStatus"
                        }
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "WT-Bot Payments API",
	Description:      "WT-Bot payments microservice for managing plans, subscriptions, and payments.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
